altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  35733854-3001-478c-8ad2-a51f04131aee:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-07T19:51:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 88624871-cb6c-463c-9890-fdd2e977341c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-08T08:13:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: e56530e2-df00-4933-94f1-671dec0d93e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e594de0-860c-4a59-8971-c5cd1bb6f133
        userCondition: null
fs: nieuwsAfbeeldingen
handle: nieuwsAfbeeldingen
name: 'Nieuws afbeeldingen'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
