columnSuffix: null
handle: leestijd
instructions: null
name: Leestijd
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: 'Lees tijd: '
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: mins
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
